### ISSUE TITLE
IndexError on color_wheel[group]

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/nwb-jupyter-widgets#145]
Example:

![fig](https://user-images.githubusercontent.com/24541631/112006333-e9f20280-8b23-11eb-9e14-1a9725b69b46.jpg)

**Comment by bendichter** [comment]
Hmm. Is there a `np.nan` here?

**Comment by bendichter** [comment]
nvm, looks like we just need to mod into that list

**Comment by luiztauffer** [comment]
worked, thanks! I'll make a PR
