### ISSUE TITLE
problem displaying images

### ISSUE THREAD

**Issue by paul-aparicio** [NeurodataWithoutBorders/nwb-jupyter-widgets#150]
Hello, 
I am having problems displaying imagesseries. I am also new to python. I am running nwbwidgets 0.6.0 on a linux machine (ubuntu). I have tried adding an ImageSeries with the data as external files to my nwb file. It shows in the acquisition tab, but trying to view it produces the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/spikes3/lib/python3.9/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/anaconda3/envs/spikes3/lib/python3.9/contextlib.py in __exit__(self, type, value, traceback)
    122         if type is None:
    123             try:
--> 124                 next(self.gen)
    125             except StopIteration:
    126                 return False

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1212                 for changes in cache.values():
   1213                     for change in changes:
-> 1214                         self.notify_change(change)
   1215 
   1216     def _notify_trait(self, name, old_value, new_value):

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    604                 # Send new state to front-end
    605                 self.send_state(key=name)
--> 606         super(Widget, self).notify_change(change)
    607 
    608     def __repr__(self):

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1225     def notify_change(self, change):
   1226         """Notify observers of a change event"""
-> 1227         return self._notify_observers(change)
   1228 
   1229     def _notify_observers(self, event):

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1262                 c = getattr(self, c.name)
   1263 
-> 1264             c(event)
   1265 
   1266     def _add_notifiers(self, handler, name, type):

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/nwbwidgets/base.py in on_selected_index(change)
    113             change.owner.children[change.new], widgets.HTML
    114         ):
--> 115             children[change.new] = nwb2widget(
    116                 list(d.values())[change.new],
    117                 neurodata_vis_spec=neurodata_vis_spec,

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/nwbwidgets/base.py in nwb2widget(node, neurodata_vis_spec, **pass_kwargs)
    238             elif callable(spec):
    239                 return vis2widget(
--> 240                     spec(node, neurodata_vis_spec=neurodata_vis_spec, **pass_kwargs)
    241                 )
    242     out1 = widgets.Output()

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/nwbwidgets/image.py in show_image_series(image_series, neurodata_vis_spec)
     91 
     92 def show_image_series(image_series: ImageSeries, neurodata_vis_spec: dict):
---> 93     if len(image_series.data.shape) == 3:
     94         return show_grayscale_image_series(image_series, neurodata_vis_spec)
     95 

AttributeError: 'NoneType' object has no attribute 'shape'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/spikes3/lib/python3.9/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/anaconda3/envs/spikes3/lib/python3.9/contextlib.py in __exit__(self, type, value, traceback)
    122         if type is None:
    123             try:
--> 124                 next(self.gen)
    125             except StopIteration:
    126                 return False

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1212                 for changes in cache.values():
   1213                     for change in changes:
-> 1214                         self.notify_change(change)
   1215 
   1216     def _notify_trait(self, name, old_value, new_value):

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    604                 # Send new state to front-end
    605                 self.send_state(key=name)
--> 606         super(Widget, self).notify_change(change)
    607 
    608     def __repr__(self):

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1225     def notify_change(self, change):
   1226         """Notify observers of a change event"""
-> 1227         return self._notify_observers(change)
   1228 
   1229     def _notify_observers(self, event):

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1262                 c = getattr(self, c.name)
   1263 
-> 1264             c(event)
   1265 
   1266     def _add_notifiers(self, handler, name, type):

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/nwbwidgets/base.py in on_selected_index(change)
    113             change.owner.children[change.new], widgets.HTML
    114         ):
--> 115             children[change.new] = nwb2widget(
    116                 list(d.values())[change.new],
    117                 neurodata_vis_spec=neurodata_vis_spec,

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/nwbwidgets/base.py in nwb2widget(node, neurodata_vis_spec, **pass_kwargs)
    238             elif callable(spec):
    239                 return vis2widget(
--> 240                     spec(node, neurodata_vis_spec=neurodata_vis_spec, **pass_kwargs)
    241                 )
    242     out1 = widgets.Output()

~/anaconda3/envs/spikes3/lib/python3.9/site-packages/nwbwidgets/image.py in show_image_series(image_series, neurodata_vis_spec)
     91 
     92 def show_image_series(image_series: ImageSeries, neurodata_vis_spec: dict):
---> 93     if len(image_series.data.shape) == 3:
     94         return show_grayscale_image_series(image_series, neurodata_vis_spec)
     95 

AttributeError: 'NoneType' object has no attribute 'shape'

When I try adding the data to the ImageSeries directly as ndarrays, I get a different message:

/home/paul/anaconda3/envs/spikes3/lib/python3.9/site-packages/nwbwidgets/image.py:102: UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-GUI backend, so cannot show the figure.
  fig.show()

Is there a way to set things so it can show these images?

Thank you for any help,
paul

**Comment by bendichter** [comment]
Hi @paul-aparicio. I think this is something we have not covered yet, but shouldn't be hard to add. I'll give it a shot and get back to you.

**Comment by bendichter** [comment]
what type of file are you reading from? a TIFF stack?

**Comment by paul-aparicio** [comment]
I tried two ways, the first was an external directory of jpegs, the second I had all of the images in a numpy array.

Thanks so much for your help!

**Comment by Saksham20** [comment]
@paul-aparicio this should work with the latest release.
