### ISSUE TITLE
Would it be possible to tag releases on GitHub please (+ pypi and master out of sync?)

### ISSUE THREAD

**Issue by sanjayankur31** [NeurodataWithoutBorders/nwb-jupyter-widgets#154]
Hello,

Thanks for nwb-widgets---they're super awesome.

I was wondering if it were possible to tag releases here on GitHub also (and if at all possible, include a Changelog for each release). I ask because when using these in platforms (for example in [NWB Explorer](http://nwbexplorer.opensourcebrain.org)), having a changelog to refer to, and tagged releases here would make it easier for developers to find what has changed in the latest release. At the moment, one has to go through the history of version.py to figure out which commit resulted in what tag, and then compare the whole commit tree to get an idea of changes between versions.

Incidentally, I also note that while pypi says that the latest version is 0.7.0, version.py here still says 0.6.0?

https://pypi.org/project/nwbwidgets/#history

https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets/blob/1ef766ea6f66dadc8c1025affd1c1f0379980b10/nwbwidgets/version.py

which seems to be from this branch (which seems like a branch to prepare the next release?)

https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets/tree/next_version

**Comment by bendichter** [comment]
@sanjayankur31 I agree a change log is a good idea. The version has been fixed on master
