### ISSUE TITLE
No module named 'spikeextractors'

### ISSUE THREAD

**Issue by MarikeReimer** [NeurodataWithoutBorders/nwb-jupyter-widgets#34]
Hello, I ran into an error when first using NWB Widgets:
![image](https://user-images.githubusercontent.com/35542396/69485632-1c3c0480-0df7-11ea-9686-a8d33d7f42a3.png)

I solved it by:
pip install spikeextractors

**Comment by bendichter** [comment]
Thanks for the report, @MarikeReimer! I just fixed this going into the future, but your fix works fine as well.

Out of curiosity, what types of data are you visualizing?

**Comment by MarikeReimer** [comment]
OMG Hi!! Right now I'm working with position data, but I am ramping on a project with 2P imaging data tracking dendritic spine changes.
